jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions: write-all  # ✅ Give write access to push changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Black (or autopep8)
        run: pip install black  # Or use 'pip install autopep8'

      - name: Format Python code
        run: black .  # Use 'autopep8 --in-place --recursive .' if using autopep8

      - name: Commit formatted code
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Auto-format code using Black" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
